name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/ || true

    
    - name: Setup DVC
      run: |
        pip install dvc[all]
        dvc pull -r origin

    - name: Train Model
      run: |
        echo "Training model..."
        python src/classification/image_classification.py

    - name: Log to MLflow/Dagshub
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        echo "Logging metrics and artifacts to MLflow/Dagshub"

  docker-build-test:
    runs-on: ubuntu-latest
    needs: build-test-train

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker image (local test only)
      run: |
        docker build -t defect-detection-app .
        docker images | grep defect-detection-app
